[package]
name = "yava"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
sevenz-rust = { version = "0.6.1", features = ["zstd"] }
xz2 = "0.1.7"
sha2 = "0.10.8"
colored = "2.1.0"
rand = "0.9.0-beta.1"
